# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efd4efd7f9f1f9035113a8ddc5ed37d5c5aaf4af146e5b43b73598cb389a9ecb77b3dd2c019d12fbaaefa5d65a7e7dea517fed0334a16f096b40c28adf477e94

test:
  secret_key_base: 11d1ca9ecc2dfdd9678f17e1fabd7a6cbb240013d66c70039f1eb97e7e761fe071aa7c6601aef32a80bfa4ec14f014adced979be2987676bcd5e6542fb31afb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
